### ISSUE TITLE
27US no WebUI

### ISSUE THREAD

**Issue by Sabotage1** [alienatedsec/yi-hack-v5#102]
Hi there, 
I've tried to install 0.3.1/0.3.0 and I get the camera to connect to the yi home app no problem.

I can't seem to get the WebUI to work... just cant reach it no matter what I try.
there for I can't really use it with HA.

Any ideas?
btw, with V3/V4 I can reach the WebUI no problem.
Thanks in advance.

**Comment by alienatedsec** [comment]
@Sabotage1 
#69 ?

**Comment by Sabotage1** [comment]
Hi, I tried port 8080 before I posted and it didn’t work.

**Comment by alienatedsec** [comment]
@Sabotage1 
#48 ?

**Comment by Sabotage1** [comment]
Oh my god ! Thx…
Finally it works with the folder on the SD CARD and it inside the camera.

Thank you and keep up the great work!
