### ISSUE TITLE
Files in sd card converted to iso

### ISSUE THREAD

**Issue by iMrLopez** [alienatedsec/yi-hack-v5#106]
All of a sudden my sd cards just show as this and my cameras are stuck in a loop. Any ideas on how to fix it? My sd card is a 16GB sd card.

![Screen Shot 2021-10-06 at 14 48 59](https://user-images.githubusercontent.com/8272737/136280971-babbfd7b-bcc0-4e9e-8cf4-91a1df7e57d9.png)

![Screen Shot 2021-10-06 at 14 50 22](https://user-images.githubusercontent.com/8272737/136281174-c806992f-6c7d-4d5d-947e-55fb2c779473.png)

**Comment by alienatedsec** [comment]
@iMrLopez I guess this is sorted, but indeed a weird one.
