### ISSUE TITLE
[yi dome 1080p] ptz page freezes 

### ISSUE THREAD

**Issue by majkers** [alienatedsec/yi-hack-v5#11]
Hello,
I have swap file enabled and still cant access PTZ page. It freezes like this:

![image](https://user-images.githubusercontent.com/21099773/114302260-81fe5e80-9ac8-11eb-885c-5aba76747847.png)

**Comment by majkers** [comment]
But. It seems to work via web service: http://IP:8080/cgi-bin/ptz.sh?dir=DIRECTION&time=TIME

**Comment by alienatedsec** [comment]
@majkers buttons (arrows) should be still operational. Please can you confirm?

**Comment by majkers** [comment]
Yes, they seem to work fine.
