### ISSUE TITLE
1080p home camera not compatible?

### ISSUE THREAD

**Issue by querex007** [alienatedsec/yi-hack-v5#111]
1080p home camera not compatible?
Orange led is not flashing after SD card insert + power on.

Information on the back of the Yi product box:
Product name: YI 1080p Home Camera
model: YYS.2016
Date: 2020.11
FCC ID: 2AFIB-YYS2016
IC: 20436-YYS2016
DID: BFUS...

Current firmware version: 9.0.19.02_202007141512

I guess I need to use the version "Yi 1080p Home | rootfs_y20 | home_y20"
I've tested the last 3 release versions, but it does not show any custom features.
SD card is formatted OK (< 32GB + fat32)
Orange led is not flashing after SD card insert + power on.

Maybe someone can confirm that yi-hack-v5 is not compatible with hardware model YYS.2016 or firmware version 9.0.19.02_202007141512?
Many thanks.

**Comment by alienatedsec** [comment]
> Maybe someone can confirm that yi-hack-v5 is not compatible with hardware model YYS.2016 or firmware version 9.0.19.02_202007141512?
> Many thanks.

https://github.com/roleoroleo/yi-hack-Allwinner-v2 if any
