### ISSUE TITLE
Crontab is not saved correctly

### ISSUE THREAD

**Issue by reef-actor** [alienatedsec/yi-hack-v5#112]
Using the web UI to add a crontab entry of `*/15 * * * * /tmp/sd/watchdog/watchdog.sh` only saves up to the first space (`*/15`). It is necessary to manually modify system.conf with the full line (which loads correctly)

v0.3.2

**Comment by alienatedsec** [comment]
@reef-actor please can you provide the example for your modification or maybe follow with the Pull Request?
