### ISSUE TITLE
1080p yi home

### ISSUE THREAD

**Issue by Raikkok** [alienatedsec/yi-hack-v5#114]
Hello
My camera serial number starts by 63US…
Fw version is 1.9.1.0J_201809191135

i copy rootfs_h20 and home_h20 in the rooth microsd (8gb fat32) but nothing happens

power on but yellow led doesnt go blurring 30seconds like instructions suggest

any help please?

**Comment by agrimpelhuber** [comment]
Hi, I'm trying to help you here, but just by stating the obvious: According to the documentation, your 63US is not supported by this firmware.

If you try to install the firmware on an unsupported version, 1 of 3 different things can happen:
- It works - in which case the list of supported cams can be updated (thanks for trying)
- It doesn't work (you case) - thanks for trying anyway
- It doesn't work, and bricks your camera (thanks for trying and saving others)

The only reason I'm stating this is to say thanks to everyone taking the risk and trying this firmware on unsupported cameras - and in the case of [Issue 119](https://github.com/alienatedsec/yi-hack-v5/issues/119), saving me from bricking my 22EU version as well.

**Comment by empatel96** [comment]
> i copy rootfs_h20 and home_h20 in the root

Did you copy over the yi-hack-v5 folder as well?
