### ISSUE TITLE
Possible to upgrade from Yi Hack V4 to this version?

### ISSUE THREAD

**Issue by Fookes74** [alienatedsec/yi-hack-v5#117]
Hi

Is it possible to upgrade from Yi cameras running Yi Hack V4 to Yi Hack V5? If it's possible but risky I'd prob leave 'as is' but if it is possible without problem I'd like to do so.

Thanks

**Comment by BigHomie90** [comment]
Format sd card and place files as instructed. Follow the next steps from the V5 guide to complete.

I tried to upgrade from v4 using user interface but no success so do it if you like by placing the files and folder directly to the root of your sd card.

**Comment by PilaScat** [comment]
Remember that the web port for v5 is 8080, I tried more and more times to install it for this

**Comment by ViktorSchlaffer** [comment]
> Hi
> 
> Is it possible to upgrade from Yi cameras running Yi Hack V4 to Yi Hack V5? If it's possible but risky I'd prob leave 'as is' but if it is possible without problem I'd like to do so.
> 
> Thanks

Yes, I just did it.

**Comment by alienatedsec** [comment]
Please follow the guidance and make sure you copy the folder.
