### ISSUE TITLE
Support for "Xiaomi Mi 360° Home Security Camera 2K Pro" (MJSXJ06CM)?

### ISSUE THREAD

**Issue by odya** [alienatedsec/yi-hack-v5#118]
Do you have plans to support new 2K xiaomi cameras? 
There is a GitHub project for cheaper version (MJSXJ05CM) but it seems to be dead https://github.com/cmiguelcabral/mjsxj05cm-hacks

**Comment by alienatedsec** [comment]
Unfortunately, no plans to support it.
