### ISSUE TITLE
Yi Home 720p 22EU Bricked Solid Yellow

### ISSUE THREAD

**Issue by monte-burns** [alienatedsec/yi-hack-v5#119]
Hi, 

I bricked my yi home camera and am trying to recover it.
I can connect to the camera via serial port and see that the yi hack v5 is installed.

But I cannot access the camera or reset it as it just stays solid yellow.
I also don't have a backup of the home partition. Is there a way around this to reinstall directly?

**Comment by brudnypiotr** [comment]
For anybody looking for hope. I've unbriked my 22EU with these files. 
[22EU_Recovery.zip](https://github.com/user-attachments/files/15748672/22EU_Recovery.zip)
