### ISSUE TITLE
sd card is not mounted?

### ISSUE THREAD

**Issue by zlotoxa** [alienatedsec/yi-hack-v5#121]
27us camera, running 1.8.7.0F_201809191400
after installing yi-hack-v5 only telnet is working.
connecting via telnet i can immediately see the following.
```
yi-hack-v5 login: root
Password:
cat: can't open '/tmp/sd/yi-hack-v5/version': No such file or directory
```
indeed, /tmp/sd is empty. 
```
/home/yi-hack-v5 # ls -a /tmp/sd
.   ..
```
i tried several different sd-cards (32gb, 2gb), reset device several times. Tried fallback to 'recovery' images, before applying v5. But result is the same. SD card is not mounted.

SD FS type is FAT32  (tried 16k and 64k block size)

Why???

**Comment by phuonglm** [comment]
I think you should try back to stock firmware then use app to check if sd card is available. Maybe hardware issue.
