### ISSUE TITLE
Yi Outdoor 1080p Wont Boot into yihack

### ISSUE THREAD

**Issue by Fajanse** [alienatedsec/yi-hack-v5#127]
Hi, I've formatted SD card (32 GB) to FAT32 (using windows and using yihome), put required files and folder into sd root directory (E:\home_h30 etc.), the camera boots into factory firmware, camera info:
Yi Outdoor Camera 1080p
Firmware: 9.0.26.07_202104231123
Model: YHS3020
Have I made some rookie mistake I'm not aware of?

**Comment by alienatedsec** [comment]
Camera not supported @Fajanse try Allwinner version
