### ISSUE TITLE
FTP Upload Facility

### ISSUE THREAD

**Issue by twosheds** [alienatedsec/yi-hack-v5#134]
Can someone explain how to set up  & use the 'FTP Upload' facility.  I've been using the FTP faciliy provided by the app 'tinyCam Pro' on my phone but the quality recorded on the FTP Server (Windows 10)  isn't very good and so I'd like to try this facilty on Yi-Hack-V5 to compare the resulting recordings. 
Thanks for any help/advice you can give.

**Comment by alienatedsec** [comment]
There will be no difference how you upload files to your FTP server
