### ISSUE TITLE
cannot connect to the web page (http://192.168.xxx.yyy:8080)

### ISSUE THREAD

**Issue by fred-c1** [alienatedsec/yi-hack-v5#135]
Hello

camera = Yi Home 27US
yi-hack-v5 version = v0.3.2

Problem: I could not connect to the web page (http://192.168.xxx.yyy:8080)

Solution:
   step 1 = reset the camera (reset button on the back of the camera)
   step 2 = (re)connect the camera using the Yi Home (Android) application

Thanks!

**Comment by fred-c1** [comment]
It worked a few days.
Now I cannot connect to the web page (http://192.168.xxx.yyy:8080)
but the Yi app. is able to connect to the camera.

I have tried several times to remove the hack and reinstall it.

Any idea?
Thanks

**Comment by Sprocket02** [comment]
I had the same issue with my Yi Outdoor cam. Unfortunatly I had to go back to v4.

**Comment by fred-c1** [comment]
@Sprocket02
Maybe some

**Comment by fred-c1** [comment]
@Sprocket02
maybe some hope:
Just after my last comment, I decided to try a 2nd uSD card.
Both cards are uSD HC 32GB
With the 2nd card I didn't check the box "quick format" (=> about 1 ??? hour to format)
I have done several reboot (web page button) and power cycling.
So far the web page and the RTSP stream have always been OK.

**Comment by fred-c1** [comment]
closed by mistake => reopen

**Comment by fred-c1** [comment]
I installed v0.3.2 hack on another Yi Home 27US today.

It seems that there is definitely a sensitivity to the model of microSD card used:
1 model of 32GB microSD cards works
2 models of 32GB microSD cards don't works (even with a partition reduced to 4GB)
1 model of 8GB microSD cards works

**Comment by 4Xsample** [comment]
I found the same problem on a 47US.
I previously had installed `Yi-Hack-v4` on this cam.
I reseted the cam.
I copied the files `home_y18` and `rootfs_y18` to a clean SD card formated in Fat32 (I used several cards to try it, 8, 16, and 32 Gb).
I start the cam with the card inside.
I Followed the process from the iPhone App to conect the cam to my network and works 100% of the installations directly with the Xiaomi app but no web acces.
When I try to log in to `http://192.168.1.156:8080` I got the message from the browser where says I can't conect there.
![Opera Instantánea_2022-01-28_045247_192 168 1 156](https://user-images.githubusercontent.com/2583302/151484524-a3722391-ef4b-46fb-a201-26633cd1e641.png)
And when I point to `http://192.168.1.156` directly with no ports I got a configuration website but with no content.
![Opera Instantánea_2022-01-28_044214_192 168 1 156](https://user-images.githubusercontent.com/2583302/151484637-381dba57-eba0-4b30-9520-dfcdca11eed6.png)
And when I try to follow any link of this website I just get no answer.
Just loading `http://192.168.1.156/?page=configurations` brings me no answer.

**Comment by fred-c1** [comment]
@4Xsample :
The instructions are "Save both files and the folder on root path of microSD card."
Did you also copy the "folder" ?
This folder is important (and often forgotten)

**Comment by 4Xsample** [comment]
I did it a couple times but not with all the cards.
I'll try it now with the 8gb one!
Let's ser if is just this...
Thanks!

**Comment by 4Xsample** [comment]
Ok!
It worked for a few hours and then went off.. 
now It does the same... 
I could conect it to homebridge for couple hours and suddently the cam went offline.
It still can be accessed from yi home app but no rtsp and the website show's the header but no work (like the image I posted)

**Comment by airart320** [comment]
Same issue here on the same hardware.
I can access the webinterface only with the initial FAT32 formatted SD. Once I format the card using the app - no access is available.
