### ISSUE TITLE
Yi Outdoor 4CCN - pairing process not valid but camera works

### ISSUE THREAD

**Issue by rcplay** [alienatedsec/yi-hack-v5#136]
Hi,
thank you very much for you work!
I have a Yi Outdoor CN version, I have successfully install the last version 0.3.2 .

The camera is it usable after the first incomplete payring via hack mode (8080 etc), but It doesn't save the conf and after reboot I need to show the qr code.

I just try by SSH with configuratio_wifi.sh

Regards

**Comment by rcplay** [comment]
No issue? Or workaround?

**Comment by MichlW** [comment]
This seems to be exactly my problem with the exact type of camera described in #315 and commented in #124.
