### ISSUE TITLE
Yi Dome 1080p web page asking for user name and password

### ISSUE THREAD

**Issue by mpaulson1961** [alienatedsec/yi-hack-v5#138]
The yi-hack-v5 instructions don't mention anything about requiring a username and password to access the camera's web page.  Is anyone else seeing this?  Is there a default username and password?

**Comment by mpaulson1961** [comment]
Tried that...  No joy.
    On Monday, January 10, 2022, 09:59:54 AM CST, fred-c1 ***@***.***> wrote:  
 
 


default = no username + no password

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pippo73** [comment]
Hi, I'm having the same problem. Is any chance to have some news?
