### ISSUE TITLE
no wifi signal

### ISSUE THREAD

**Issue by evo11x** [alienatedsec/yi-hack-v5#139]
I have flashed the correct firmware for YI 1080p Home, and now it says waiting to connect, but I cannot find it's wifi ssid from the phone or computer and I don't want to use their app to connect so that it will send again my router password to the cloud.

Update:
I have tried to connect with the Yi Home App, and after the camera scans the QR code from the app it says wifi connected, but the app does not see the camera and gives a timeout before finalizing the connection. Then the camera enters again in waiting for connection mode.
The camera responds to ping before the timeout, but I cannot access it with http://x.x.x.x:8080 I get connection refused.

**Comment by bluehz** [comment]
I have this same issue on a 27US

**Comment by alienatedsec** [comment]
#238 check this
