### ISSUE TITLE
45CN - connect to wifi

### ISSUE THREAD

**Issue by Desease87** [alienatedsec/yi-hack-v5#14]
I used yi-hack-v4 0.2.0 Crypto before installing this version and I needed to use the Chinese version app to generate QR to connect my camera to wifi. After installing this version of the hack, I need to use the global version application, because the QR from the Chinese version, turn the camera back and block it with the text that "this camera can only be used in the Chinese region."

**Comment by alienatedsec** [comment]
The same as #49 I would need a CN camera in order to test. Any ideas where to get one? @Desease87
