### ISSUE TITLE
How to convert from MStar hack to yours?

### ISSUE THREAD

**Issue by idanny76** [alienatedsec/yi-hack-v5#142]
Trying to flash your firmware over roleoroleo /yi-hack-MStar for my 1080P Yi Dome BFUS | 4.6.0. Copied your files to the sd card, but the firmware did not flash. Is is possible to overwite Yi-Hack from one builder to another?

**Comment by idanny76** [comment]
> Did you copy over the folder from the release as well?

Yes the two files and the folder. It did not write over the current firmware.

**Comment by idanny76** [comment]
The only way I can get it to read the new firmware is by renaming these files, but it will flash and then get stuck flashing. Then I have to re-flash the other firmware.
home_h201c to home_h20
sys_h201c to rootfs_h20

**Comment by gelse** [comment]
i have the exact same behaviour as @idanny76

**Comment by fred-c1** [comment]
Could be useful:
https://github.com/shadow-1/yi-hack-v3/issues/215
in particular:
"To REMOVE the hack, requires 2 files on the SDCard root with the following naming conventions:"

**Comment by gelse** [comment]
@fred-c1 thanks, i already checked that - Yi seems to have removed the original firmware from their website.

**Comment by alienatedsec** [comment]
@idanny76 this hack (v5) wont work on MStar cameras
