### ISSUE TITLE
compatibility with r40ga QFUS model 1080p outdoor PTZ camera

### ISSUE THREAD

**Issue by drdetergent** [alienatedsec/yi-hack-v5#143]
Hi
I have the r40ga QFUS model 1080p outdoor PTZ camera and looks out of the compatible list.

Any chance to include it? I believe this is a great value camera and available at [very good price of €60](https://www.aliexpress.com/item/1005002205428193.html).

I see that was compatible as [beta in Allwiner2 by roleoroleo](https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/master/README.md) and maybe is easy to include in this fresh new release if yi-hack-v5

Please count on me for testing and with a bit of instructions, for building and testing this new firmware.

Thank you.

**Comment by alienatedsec** [comment]
Anything `xFUS` is not supported by this hack - Allwinner chipset
