### ISSUE TITLE
How to automatically reboot cameras

### ISSUE THREAD

**Issue by kirilldem** [alienatedsec/yi-hack-v5#147]
I would like to automatically reboot cameras once a week to make sure there are no glitches. I have tried to test the crontab with
 `46 20 * * * reboot now` 

![image](https://user-images.githubusercontent.com/44521162/151714995-23758dfd-b4b3-4291-8d39-e0fc23cd70c0.png)

After I reload the page only 46 is shown, so I don't think it is saved. Am I doing something wrong? Is there another way to reboot on schedule?

![image](https://user-images.githubusercontent.com/44521162/151715012-234b6458-4cc8-4ffa-bd63-e1b745edbed7.png)

**Comment by reef-actor** [comment]
Caused by issue #112 
You can change the set_configs.sh like in pending PR #113 to allow saving the full line

**Comment by kirilldem** [comment]
Thanks for pointing me to the workaround.

**Comment by kirilldem** [comment]
> Caused by issue #112 You can change the set_configs.sh like in pending PR #113 to allow saving the full line

How would I actually use the delimiter on the settings page?

I'd like to have this cron command `46 20 * * * reboot now`

**Comment by reef-actor** [comment]
the changes in the pr fix the way the script saves text, allowing saving entries with spaces in them. so you should be able to save it just as you have typed

**Comment by kirilldem** [comment]
> the changes in the pr fix the way the script saves text, allowing saving entries with spaces in them. so you should be able to save it just as you have typed

Hey reef-actor, 

I never actually managed to get this working. The PR you linked to has not been merged in the latest release right? 

As a workaround, I see that I can manually edit system.conf. I just edited it in WinSCP but the camera wouldn't boot so I assume  I need to add the cron command with inverted commas? Or perhaps it should be edited as sudo?

`CRONTAB=46 20 * * * reboot now`

Any help is greatly appreciated :)
