### ISSUE TITLE
Optimize cron service and fix issue in cron file generation

### ISSUE THREAD

**Issue by eladiogalvez** [alienatedsec/yi-hack-v5#150]
Possible will be better if try to start only one cron service and also after every restart add lines duplicated with schedulled tasks in file that generate stability issues.

![6C7FF243-8413-4E21-99EA-3FB7AC890739](https://user-images.githubusercontent.com/22935476/153718933-80c1d1e4-14bf-4dba-b26e-0b5834745b36.jpeg)

**Comment by eladiogalvez** [comment]
Possible option is in file system.sh:

**/tmp/sd/yi-hack-v5/script/system.sh**
```
echo "1 1 * * * $YI_HACK_PREFIX/script/check_update.sh" > /var/spool/cron/crontabs/root                     
if [ ! -z "$CRONTAB" ]; then                                                                                
 echo "$CRONTAB" > /var/spool/cron/crontabs/root                                                            
fi                                                                                                          
if [ "$FREE_SPACE" != "0" ]; then                                                                           
    echo "0 * * * * /tmp/sd/yi-hack-v5/script/clean_records.sh $FREE_SPACE" >> /var/spool/cron/crontabs/root
fi
...
#crond -c $YI_HACK_PREFIX/etc/crontabs                                                                      
```

**Comment by eladiogalvez** [comment]
Possible can be interesting add to web disable/enable updates check's

**Comment by lupo-ch** [comment]
Hello, thank you very much for this BUG report! 
This problem flooding my /var/spool/cron/crontabs/root with 20-30 and more one and the same lines caused my cameras to freeze when the  SD free space (%) is reached and the OS try to execute 20-30+ delete commands in the same second ... :( 

0 * * * * /tmp/sd/yi-hack-v5/script/clean_records.sh 1
0 * * * * /tmp/sd/yi-hack-v5/script/clean_records.sh 1
0 * * * * /tmp/sd/yi-hack-v5/script/clean_records.sh 1
....

I have fixed the problem as you suggested changing line 258 in /tmp/sd/yi-hack-v5/script/system.sh
from 
echo "0 * * * * /tmp/sd/yi-hack-v5/script/clean_records.sh $FREE_SPACE" >> /var/spool/cron/crontabs/root
to
echo "0 * * * * /tmp/sd/yi-hack-v5/script/clean_records.sh $FREE_SPACE" > /var/spool/cron/crontabs/root

Good Luck!
:) :) :)
