### ISSUE TITLE
YI IOT camera YI01-1080P-WH

### ISSUE THREAD

**Issue by Remc000tje** [alienatedsec/yi-hack-v5#152]
Hi all,
I was wondering if any YI-Hacks will work.
I recently bought this one (https://yiiot.net/) from China , but of course the earning model is in selling cloud-storage. 
I would really want to RTSP the stream. 

the firmwareversion is: 5.0.00.00_202110181025
in the connection section of the app it states:
1. *.*.68.45:32100
2. *.*.92.23:32100
3. *.*.175.16:32100
4. *.*.75.113:443
5. *.*.69.18:443
6. *.*.137.202:443

any suggestions?

kind regards,
Remco

**Comment by vliopard** [comment]
I bought YI-1080-WH but it works only with YI IoT app. 
I am looking for a way to enable that working with other apps like YooSee/YCC365 and similar. Does anyone know if that is possible?

**Comment by hadarge** [comment]
+1

**Comment by lotech** [comment]
+1
