### ISSUE TITLE
1080p Yi cameras and FPS confusion

### ISSUE THREAD

**Issue by iointerrupt** [alienatedsec/yi-hack-v5#158]
I have a couple of Yi 720p 47US cameras that I use completely off cloud (no Yi App, no internet, local IoT VLAN only and RTSP recording).  I am holding off on upgrading to the 1080p models because I am bit confused as to whether to 1080p smart home and/or dome support frame rates >= 25.  I checked Amazon and reviews where some say yes and some say no.  Yi's website doesn't mention FPS either.

Also, if the yi cameras do support it, is Yi-Hacks-v5 able to stream 1080p with fps >= 25 since it uses a custom rtsp stream server app? Can the firmwares work without internet and local only like my current scenario?  Thus far I've held off on upgrading because of the low fps and no knowledge of its ability to work completely without cloud and internet.

Thanks for this great firmware btw.

**Comment by fidesachates** [comment]
I'm also interested in whether 1080p Smart Home is supported at all.
