### ISSUE TITLE
[Yi Outdoor 1080p] Testing to Confirm Compatibility

### ISSUE THREAD

**Issue by databoy2k** [alienatedsec/yi-hack-v5#16]
I see I'm not the only one with an outdoor cam over here (thanks for doing this, by the way). I've installed it on a pair of cameras and it seems to be working.

What tests or information do you need from us to confirm compatibility?

**Comment by tannd155** [comment]
Hi databoy2k,

It's good to hear that as I also have a Yi outdoor camera. I'm looking forward to a stable version of this hack to install on my camera.

Currently, I'm using the v4 hack for the camera and found the connection via RTSP is not stable. So I hope that the v5 with the swap file will help to solve this out.

**Comment by majkers** [comment]
Could you please check MQTT?

**Comment by alienatedsec** [comment]
Thanks for testing. Other than that, please report only new issues only. There are quite a few already.
@databoy2k

**Comment by alienatedsec** [comment]
Closing as not an issue
