### ISSUE TITLE
Send custom telemetry to the camera 

### ISSUE THREAD

**Issue by Pamapama** [alienatedsec/yi-hack-v5#160]
Hi, 

any chance to add a feature so that the camera can receive telemetry and save that as part of the video? 
At the moment I have to use an RTMP stream to a small PC and overlay the telemetry as an HTML page in OBS to keep everything in sync. But if there is a chance to send the data to the cam and store it in the video file that would be awesome.

**Comment by alienatedsec** [comment]
I am far from introducing new functions. See https://github.com/alienatedsec/yi-hack-v5/issues/88#issuecomment-1088595542

However, if you have seen any project which adopts it already, I can have a try
