### ISSUE TITLE
FTP Upload not working

### ISSUE THREAD

**Issue by iointerrupt** [alienatedsec/yi-hack-v5#162]
I have 2 Yi Home 720p cameras with the hack working well. I can view RTSP streams and get MQTT motion notifications.  I have cloud access disabled.  I have a remote FTP server set up receive videos from the cameras and enabled "FTP Upload" enabled under events but it appears nothing happens with this.  No videos are sent to the FTP server nor are stored on the SD cards on the cameras.  The cameras are 47US.

Additionally, is there a way to lower the motion off notification to anything under one minute?

EDIT: Here is a copy of my settings from system.conf (edited to remove personal info)
```
HTTPD=yes
TELNETD=no
SSHD=yes
FTPD=no
BUSYBOX_FTPD=no
DISABLE_CLOUD=yes
REC_WITHOUT_CLOUD=yes
MQTT=yes
RTSP=yes
RTSP_STREAM=high
RTSP_AUDIO=no
ONVIF=no
ONVIF_WSDD=no
ONVIF_PROFILE=high
ONVIF_NETIF=wlan0
ONVIF_WM_SNAPSHOT=no
NTPD=yes
NTP_SERVER=*************
PROXYCHAINSNG=no
SWAP_FILE=no
RTSP_PORT=554
ONVIF_PORT=37777
HTTPD_PORT=8080
USERNAME=*************
PASSWORD=*************
TIMEZONE=America/*******
FREE_SPACE=0
FTP_UPLOAD=yes
FTP_HOST=***************
FTP_DIR=/cams/nanny/
FTP_DIR_TREE=yes
FTP_USERNAME=**********
FTP_PASSWORD=**********
FTP_FILE_DELETE_AFTER_UPLOAD=yes
CHECK_UPDATES=no
SSH_PASSWORD=*****
CRONTAB=

```

**Comment by joseantgv** [comment]
Any update on this?

**Comment by alienatedsec** [comment]
@joseantgv @iointerrupt 
My 47US is storing videos on the SD CARD with no problem. I will look closer to FTP upload.

**Comment by alienatedsec** [comment]
Working with v0.3.3
If your cameras are not saving videos, please format the card in the YI app and put back the `yi-hack-v5` folder, restart and check again.
