### ISSUE TITLE
Can I change SD after flash

### ISSUE THREAD

**Issue by bumpengrinder** [alienatedsec/yi-hack-v5#163]
Hi

I have just flashed yi-hack-v5 using an 8GB SD card.  I would now like to swap it for a bigger card for recording.  Can I just swap to a clean SD or do the install files need to be on the card for yi-hack-v5 to work?

Thanks

**Comment by KaraFR** [comment]
I would say no.

I just formatted the SD via the YI Home app and now the webserver is inaccessible :(

**Comment by bumpengrinder** [comment]
> I think you just has to copy the "yi-hack-v5" folder in the new SD (works for me)

Brilliant, that worked thank you!
