### ISSUE TITLE
This is a fix for issue Disable Cloud and not record after that

### ISSUE THREAD

**Issue by sabixr** [alienatedsec/yi-hack-v5#164]
test on Yi 1080p Home 48US

If you have a problem like I do (after disabling the cloud, the camera doesn't record any video), change the code above to fix the issue with recording after disabling the cloud function in the web interface.

Using ssh

vi /tmp/sd/yi-hack-v5/script/system.sh

edit this line of code (line 117)from This:
-----------------------------------------------------------------------------
elif [[ $(get_config REC_WITHOUT_CLOUD) == "yes" ]] ; then
    (
        cd /home/app
        sleep 2
        ./mp4record &
    )
fi

------------------------------------------------------------------------------
to This:
------------------------------------------------------------------------------
elif [[ $(get_config REC_WITHOUT_CLOUD) == "yes" ]] ; then
    (
        cd /home/app
        sleep 2
        ./mp4record &
        ./cloud &
        sleep 5
        killall -1 cloud
    )
fi
------------------------------------------------------------------------------

You can also do this on pc by attach microsdcard to pc and using notepad
goto this location:
yi-hack-v5/script/system.sh
edit code same as above

I hope this can help you

**Comment by g1za** [comment]
I had the same issue with my Yi Dome 720p camera

Firmware Version | 0.3.2
Base Version | 1.9.1.0J_201809191135
Model Suffix | yi_dome
Hardware ID | 63US

This change in the code fixed the problem for me.
Thanks @sabixr 

@alienatedsec you may want to have a look

**Comment by leioo2000** [comment]
I have the same issue with my Yi Dome 1080p camera

Firmware Version	0.3.2
Base Version	1.9.2.0I_201812141405
Model Suffix	yi_dome_1080p
Hardware ID	65CN

This change in the code unfortunately doesn't work in my case.

![image](https://user-images.githubusercontent.com/41536811/186444745-6da2d67b-cd63-45f3-8afd-b0ec9f3ecb7f.png)

**Comment by leioo2000** [comment]
I think I found the cause why it didn't work even after the above code update: the "Proxychains-ng" option must be turned OFF! only leave "Disable Cloud" and "Recording without Cloud" on. (if your camera is region locked after proxychain off, try turn on "Disable Cloud" first.)

![image](https://user-images.githubusercontent.com/41536811/186453924-25b66740-eda4-494e-9cca-57f623f55a98.png)

**Comment by g1za** [comment]
Just for the records, I never enabled that option and the code fix was enough for me.
