### ISSUE TITLE
password

### ISSUE THREAD

**Issue by tunerooster** [alienatedsec/yi-hack-v5#17]
On a Yi Outdoor, after installing yi-hack-v5 **_OVER_** yi-hack-v4, it is all working (so far) except I am unable to set the root password:
- Via the Config web page.
- Via running `passwd root` from the command line.
From the command line, running (as root):
```
passwd
New Passwd: mypw
passwd: warning: can't create backup copy '/etc/passwd-': Invalid cross-device link
passwd: Device or resource busy
passwd: can't update password file /etc/passwd
```
From the Config web page, entering a password simply did not take.  After saving and rebooting, the password remains null.

Please note, _this only fails when installing yi-hack-v5 over an existing yi-hack-v4 install_.  When I installed it on a new camera with no existing hack, it worked.

Please advise if there are any work-arounds.

Thanks!

P.S. I notice that there is a passwd file in ~/etc/passwd on the Allwinner version of the hack _for the Indoor cameras_ (which_ appears to be a clone of /etc/passwd).  There is no ~/etc/passwd in the 0.3.0 yi-hack-v5 release.  Maybe this is related to the problem.

**Comment by majkers** [comment]
In https://github.com/alienatedsec/yi-hack-v5/issues/9 I updated directly from theCrypt0 hack

**Comment by tunerooster** [comment]
@majkers, what do you mean you "updated directly from theCrypt0 hack"?

Is there a work around from theCrypt0 v4?  If so, what did you do?  Thanks!

**Comment by majkers** [comment]
I mean before applying yi-hack5 I had theCrypt0 original hack without @alienatedsec fork of it.

**Comment by tunerooster** [comment]
Understood.  Me too.  Does changing the password work for you?

**Comment by alienatedsec** [comment]
@tunerooster @majkers

`umount /etc/passwd` then you can run `passwd` to set a new password

I got a fix for the next release to make it happen through WebUI
