### ISSUE TITLE
WiFi connection QR code routine - always. Do not want to save wifi credential 

### ISSUE THREAD

**Issue by SergeyKalinichenk** [alienatedsec/yi-hack-v5#173]
YI-HACK-V5 v0.3.2 - BETA
yi_dome
13CN

I am trying to save wifi credential using camera web page
but it didnt saving it

wifi connection routine is always the same - qr code :(

**Comment by Staini** [comment]
Try to create a custom wpa_supplicant.conf:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/289
