### ISSUE TITLE
No events or records on Yi 47US

### ISSUE THREAD

**Issue by Helloamiral** [alienatedsec/yi-hack-v5#177]
Hello,

I have no events or records on Yi 47US :

Firmware Version | 0.3.2
Base Version | 1.8.7.0F_201809191400
Model Suffix | yi_home
Hardware ID | 47US

eventsdir.sh :
{"records":[
]}

This issue did'nt work :  https://github.com/alienatedsec/yi-hack-v5/issues/164

How to solve this mistake ?

Thanks

**Comment by alienatedsec** [comment]
@Helloamiral Please format the card in the YI app, copy the `yi-hack-v5` folder to its root and restart the camera.
