### ISSUE TITLE
New Release to use low resolution for motion snapshot on OutDoor Camera

### ISSUE THREAD

**Issue by Minims** [alienatedsec/yi-hack-v5#181]
Is it possible to make a new beta release to test the PR https://github.com/alienatedsec/yi-hack-v5/pull/169 from @reef-actor
Thanks ! :-)

**Comment by alienatedsec** [comment]
@Minims I am sorry for such a long response, but now I am slowly getting back on this project.

**Comment by alienatedsec** [comment]
@Minims Please upgrade to v0.3.3

**Comment by Minims** [comment]
Works great.
Thanks !
