### ISSUE TITLE
yi_cloud_dome_1080p doesn't run when ifz ether is connected

### ISSUE THREAD

**Issue by rubendediegomartinez** [alienatedsec/yi-hack-v5#185]
yi_cloud_dome_1080p doesn't run when ifz ether is connected.
![image](https://user-images.githubusercontent.com/82880022/180457440-412a4d6d-fcd6-44cd-af17-100482542fc6.png)
As you can see, when ether ifz is connected the firmware can't get the IP address and the rest of parameters
Thanks

**Comment by alienatedsec** [comment]
> As you can see, when ether ifz is connected the firmware can't get the IP address and the rest of parameters

@rubendediegomartinez please can you explain the above in detail? I have difficulties decrypting the message, especially when I have no camera.
