### ISSUE TITLE
Change WiFI SSID does not work - Camera reboots attached to original SSID after update through UI (also with configure_wifi.sh script)

### ISSUE THREAD

**Issue by Cisor** [alienatedsec/yi-hack-v5#186]
Steps to reproduce issue:

- http://camaddress:8080/?page=wifi
- Select network from "WiFi network ESSID"
- Enter password 
- Enter password confirmation
- Open browser console to Network tab
- Save
- http://camaddress:8080/?page=reboot
- "Reboot Camera"

Behaviour:
- "Saved" on wifi page
- Camera returns - 
```
{
"error":"false"
}
```
- Camera reboots attached to previous network

Expected:
- Camera reboots attached to new network

------------------------------------------

Also 
- echo "wifi_psk=thepasswordstring" >> /tmp/configure_wifi.cfg
- echo "wifi_ssid=thessidstring" >> /tmp/configure_wifi.cfg
- ./script/configure_wifi.sh
- /tmp/sd/yi-hack-v5/www/cgi-bin/reboot.sh
This outputs the file /tmp/sd/mtdblock2_20220731175303.bin containing the original credentials but there is no change after the reboot. Still attached to old wifi

**Comment by alienatedsec** [comment]
@Cisor Which camera model do you have?

**Comment by Cisor** [comment]
I knew I forgot something!
It is a Yi Dome

**Comment by alienatedsec** [comment]
There have been a few changes since you raised this issue. Please can you try `0.3.7`?

**Comment by Cisor** [comment]
I appreciate the follow up, thanks. I will test this, although it's not likely to be within a fortnight
