### ISSUE TITLE
ONVIF - can't reboot the camera from Home Assistant

### ISSUE THREAD

**Issue by lechoooo** [alienatedsec/yi-hack-v5#187]
ONVIF provides an option to reboot the camera from Home Assistant, but after running the option nothing happens. Same option works on my second camera with yi-hack-mstar. 

The ONVIF server is enabled on the camera, Home Assistant recognized it, and I can even see the live feed from camera.

Anybody had similar problems?

**Comment by alienatedsec** [comment]
@lechoooo 
Do you have any logs available? Folders are different on v5, and commands would also work differently. Any chance to get the command that is executed?
