### ISSUE TITLE
Upgrade from yi-hack-v4

### ISSUE THREAD

**Issue by JustALoOp** [alienatedsec/yi-hack-v5#188]
![image](https://user-images.githubusercontent.com/77412932/182915832-5f970361-744c-4aa9-8325-80bdffb54325.png)

Hi, I wanna ask if I can just use Flash Image via web in yi-hack-v4 to upgrade to v5?

Thanks in advance!

**Comment by alienatedsec** [comment]
@JustALoOp You could, but please remember to save the yi-hack-v5 folder on the SD-CARD too.
