### ISSUE TITLE
No information displayed on main screen

### ISSUE THREAD

**Issue by kapabel** [alienatedsec/yi-hack-v5#189]
Hello! What’s wrong when on the main page I only get displayed whats in the section "Links". All other information is empty like host name, serial number, wifi name etc.
It was working once and since I changed the sd card it isn’t anymore. I have tried to reflash the camera but nothing seems to be working.

**Comment by alienatedsec** [comment]
Please paste the screenshot

**Comment by kapabel** [comment]
Closed.
