### ISSUE TITLE
Adding "s" to all mqtt attribute values starting with "s"

### ISSUE THREAD

**Issue by tunerooster** [alienatedsec/yi-hack-v5#19]
Strange one...

Each time the MQTT changes (from the web page) are saved, all attribute values which begin with "s" get an additional "s" prepended.  For example: `TOPIC_BIRTH_WILL=status` becomes `TOPIC_BIRTH_WILL=sstatus` then `TOPIC_BIRTH_WILL=ssstatus` if changes is saved twice.  Same for `sound_detection` and `sound_detected`.

**Comment by majkers** [comment]
Yes. I hade the same effect. Confirm that one. I switche to manually edit mqtt setting from file.
