### ISSUE TITLE
Increasing space available on firmware root

### ISSUE THREAD

**Issue by iointerrupt** [alienatedsec/yi-hack-v5#197]
I noticed that the firmware root is by default using about 93% space from the get go.  If we move **non-critical** files from the root (/) to the sd card, we can further increase space on the root firmware.

Example: There are standard linux config files like `/etc/services`, `/etc/profile`, `/etc/protocols`.  If we move those to a folder in the sd card, like `/tmp/sd/yi-hack-v5/etc/` and symlink `/etc/services`->`/tmp/sd/yi-hack-v5/etc/services`.  We have added additional space, ~20KB to the firmware root.

Obviously for system stability, its important to keep files in folders like `/bin` (which are symlinked to busybox), or the kernel driver (.ko) files in the `/home/base` folder intact.  But I'm wondering if it might be beneficial to move other files, especially some of the large binaries in the `/home/app` to the SD card?

**Comment by alienatedsec** [comment]
I see it as viable, but this will kill the camera if no SD is inserted. The biggest part is Busybox; compressing or decreasing its size would be the only beneficial approach.
