### ISSUE TITLE
YI Home 1080 47 US - not able to save config or mqtt

### ISSUE THREAD

**Issue by Domip2** [alienatedsec/yi-hack-v5#198]
yi-hack-v5 - v0.3.4 - BETA  and 0.3.3

YI Home 1080 47 US - I am not able to save config or mqtt.

If i change something in config, save and reboot the settings are gone.
If i change something in mqtt, save and reboot the interface is not reachable via 8080 any more.

Tryd Firefox, Edge and Chrome. Same results.

Best regards and thank you!

**Comment by alienatedsec** [comment]
I have the same model - no issues. Check files are not read-only or have some weird permissions.
