### ISSUE TITLE
[Yi Outdoor 1080p] Booting without microSD card

### ISSUE THREAD

**Issue by fscsantos** [alienatedsec/yi-hack-v5#20]
The camera doesn't boot without the microSD card after flashing.
Just to confirm that this is a bug and not by design.

Because of this recording can't be activated from the official App as the card needs to be formatted.

**Comment by alienatedsec** [comment]
@fscsantos it does boot but has no cloud functionality at all. It looks like it needs the `yi-hack-v5` folder. I will need to review where the issue is.

Thanks for raising

**Comment by fscsantos** [comment]
Sorry for misleading. I tried both SSH and the web interface and couldn’t access them. 
But I confirm that it was connected to the Wi-Fi and I cloud ping it.
