### ISSUE TITLE
initial install cam wont eat firmware 

### ISSUE THREAD

**Issue by FuriousFowl** [alienatedsec/yi-hack-v5#205]
Iv got a box of these things both home 1080p and outdoor... i cant get the initial install to kick off. theyre currently on firmware 8.2

i tried to get v4 to work last spring with the same results...  nothing, figured id give it another shot with a new version

the files are naked and unchanged in the root dir of the 16gb sd card. the cameras just ignore that shit and keep on as usual

i attempted to downgrade back to stock with the recovery package from yi-hack 3, thinking it would have no reason to upgrade from a lower firmware, maybe i needed to take it back to bare bones...nothin

bro, im no noob and its really chappin my ass that im failing at something so simple as "put the card in and power on"

so now i'm forced to do the unthinkable... ask for help

**Comment by alienatedsec** [comment]
Sorry, unsupported chipset - try allwinner hacks @FuriousFowl
