### ISSUE TITLE
Privacy status unavailable

### ISSUE THREAD

**Issue by g1za** [alienatedsec/yi-hack-v5#211]
Hello,
Has anything changed with version 0.3.5?
I installed "yi-hack_ha_integration" but the privacy switch made available by this custom integration is unavailable since that upgrade.
Thanks

**Comment by g1za** [comment]
Also camera entity made available by the same seems to be broken.

**Comment by alienatedsec** [comment]
Yes @g1za - https://github.com/alienatedsec/yi-hack-v5/commit/44da7e79c5eb8399e3543eb8df17dcd236be502b

I'll have a look tomorrow when free

**Comment by alienatedsec** [comment]
@g1za Can I have a screenshot from your HA? I never used this integration, but happy to make it right.

Mine was added successfully but shows offline - I cannot see any other sensors and functionalities like the `privacy switch` or even the `RTSP` stream.

![image](https://user-images.githubusercontent.com/73167064/205865227-be168594-a2e7-40a1-9b21-e09338561f9e.png)

**Comment by alienatedsec** [comment]
I think I know what I did - let me test it.

**Comment by g1za** [comment]
Thanks, just in case please see my screenshots

![Schermata 2022-12-06 alle 11 28 11](https://user-images.githubusercontent.com/88257868/205887045-b926bd9a-58cc-42bb-9e4f-61d57dbb983e.png)

![Schermata 2022-12-06 alle 11 25 41](https://user-images.githubusercontent.com/88257868/205887107-06b44d85-1970-404c-8d29-a04531303148.png)

![Schermata 2022-12-06 alle 11 26 14](https://user-images.githubusercontent.com/88257868/205887187-06eb1468-a0eb-4a14-907d-20922b05bbbf.png)

![Schermata 2022-12-06 alle 11 26 21](https://user-images.githubusercontent.com/88257868/205887216-83f372b0-c268-4db7-9d96-20f1243adbc3.png)

![Schermata 2022-12-06 alle 11 26 33](https://user-images.githubusercontent.com/88257868/205887243-bd21fa2a-bed6-4478-b38e-a9d0b7a04638.png)

**Comment by g1za** [comment]
And also (I disabled some as not applicable for my old Yi Dome or because taking too many resources - disabled on MQTT page FW as well) 

![Schermata 2022-12-06 alle 11 36 24](https://user-images.githubusercontent.com/88257868/205889019-88ba8dba-810a-4864-a887-b10c7f6e5072.png)

**Comment by g1za** [comment]
Thank you. It's back to normal now.

About swap file:

Short answer: not sure if I need it but yes, I use it.

Long answer: for my platform I think it's enabled by default (20% if I remember correctly), anyway I turn the option on. Some time ago I had an issue and manually increased to 60 Then the problem disappeared (probably some issues with the SD card) and I didn't worry too much about that anymore (I also think that recent updates may have turned it back to default values).
If your question is related to performance on my platform: if I disable anything I do not need (ONVIF, on MQTT I delete the suffixes that are not applicable to me -  I read somewhere this is the bulletproof way to save resources) it is quite stable now. Only from time to time the camera enters a motion detection loop and it starts and keeps recording... if I reboot the camera it goes back to normal (not sure if it a problem of the camera or of the integration I use).
I may try to switch to RTSP high res and see what happens.

Thanks again.
