### ISSUE TITLE
Webpage does not detect 0.3.5(or newer) release

### ISSUE THREAD

**Issue by t0ny-peng** [alienatedsec/yi-hack-v5#214]
I have a Yi Dome 1080P camera. It's currently running 0.3.4. In the Service page after I click `Online FW upgrade`, the available version is always blank after a while

<img width="830" alt="Screen Shot 2022-12-06 at 12 46 54 PM" src="https://user-images.githubusercontent.com/4816327/206019806-6a5645c6-3950-4d1c-ba70-3e7e62c45649.png">

A minute later, another error popped up.

<img width="683" alt="Screen Shot 2022-12-06 at 12 48 28 PM" src="https://user-images.githubusercontent.com/4816327/206020031-08798b39-e025-4d03-8465-b7e21087b751.png">

Is there a way to update the firmware manually via copying to micro SD card? Thx!

**Comment by alienatedsec** [comment]
It must be something wrong with your network (e.g., pihole or other DNS or internet access for that specific device issue)

Copy your respective file to `/tmp/sd` and rename the file `version part` to `yi_dome_1080p_x.x.x.tgz`

Then paste the following in the browser `http://IP:8080/cgi-bin/fw_upgrade.sh?get=upgrade` and press enter. Wait for `Firmware Downloaded` message which will also start the upgrade process on the camera.

**Comment by t0ny-peng** [comment]
@alienatedsec You are definitely right. I forgot I added a firewall rule to these cameras. Everything working fine after the firewall rule is disabled.
