### ISSUE TITLE
The sound speed is too fast when playing

### ISSUE THREAD

**Issue by wangxu8611** [alienatedsec/yi-hack-v5#217]
Video recorded via rtsp. The sound speed is too fast when playing. The video time is 60 seconds and the sound time is 25 seconds after the sound and picture are separated

**Comment by wangxu8611** [comment]
Im sorry。
The video stored in the SD card is recorded by the camera itself, not by rstp

**Comment by alienatedsec** [comment]
Which hack version and camera do you use?

**Comment by wangxu8611** [comment]
release： yi_home_1080p_0.3.7.tgz
camera model：YYS.2016.CN

Firmware Version | 0.3.7
Base Version | 2.1.0.0E_201809191630
Model Suffix | yi_home_1080p
Hardware ID | 48CN

**Comment by wangxu8611** [comment]
If you need my video file, I can send it to you by email

**Comment by alienatedsec** [comment]
weird - mine is a few seconds delayed, but I am testing a new version.

Please send to alienatedsec@gmail.com

**Comment by wangxu8611** [comment]
file has been sent and one more issue about onvif

**Comment by alienatedsec** [comment]
Does it work fine on your mobile?

**Comment by wangxu8611** [comment]
手机看回放视频，声音也是断断续续的
Watch the playback on the mobile APP, and the sound is intermittent。
感觉像是芯片性能不够，导致的声音断续。
It seems that the sound is intermittent due to insufficient chip performance.
开启rtsp以后，感觉后端网站打开速度都变慢了很多。
After starting rtsp, I feel that the backend websites are much slower.

**Comment by alienatedsec** [comment]
So, the final thought about what SD card is in the camera?

**Comment by wangxu8611** [comment]
![image](https://user-images.githubusercontent.com/120047259/206886254-0d323706-24a3-49a0-962b-f843ae47e748.png)
class10

**Comment by alienatedsec** [comment]
[hdparm.zip](https://github.com/alienatedsec/yi-hack-v5/files/10203088/hdparm.zip)

Please unpack the `hdparm` to `/tmp/sd` and execute it as per the below:
`./tmp/sd/hdparm -Tt /dev/mmcblk0p1`

The below is my reading
```

/tmp/sd # ./hdparm -Tt /dev/mmcblk0p1

/dev/mmcblk0p1:
Timing buffer-cache reads:    12 MB in 0.56 seconds = 21890 kB/s
Timing buffered disk reads:   14 MB in 3.24 seconds = 4422 kB/s
/tmp/sd #

```
