### ISSUE TITLE
Minor typo in imggrabber debug output. Missing () after current_timestamp

### ISSUE THREAD

**Issue by tburtenshaw** [alienatedsec/yi-hack-v5#221]
Very minor typo.

This would only affect the output when playing with `imggrabber --debug` as the function `current_timestamp` is missing parentheses so it prints location of function rather than running the function and displaying output.

https://github.com/alienatedsec/yi-hack-v5/blob/0b6b63a9492a283180543349d28f6e8b176cccb8/src/snapshot/snapshot/imggrabber.c#L719

**Comment by alienatedsec** [comment]
What the line should look like @tburtenshaw . Is the below correct?

``` if (debug) fprintf(stderr, "%lld - frame found, exit loop\n", current_timestamp());```
