### ISSUE TITLE
yi-hack-v5 - v0.3.1?

### ISSUE THREAD

**Issue by tunerooster** [alienatedsec/yi-hack-v5#24]
The _Update_ page on the web interface says the "Remote Version" is at 0.3.1 and the "Local Version" is at 0.3.0.  Yet there is no 0.3.1 on the "releases" link.

Is there really a 0.3.1 release?  I am anxiously awaiting the mqtt motion event fix.

Thanks!

**Comment by alienatedsec** [comment]
Hi @tunerooster 

Send me a message on Discord and you could get this release for testing if you wish.

**Comment by tunerooster** [comment]
Is `ipc_multiplexer` implemented in 0.3.1?  (I.e., is MQTT motion messages implemented?)  If so, is there a group, or ID I can reference to message you on Discord?  I not much familiar with Discord...  Thanks!

**Comment by alienatedsec** [comment]
@tunerooster yes
