### ISSUE TITLE
Not flashing firmware

### ISSUE THREAD

**Issue by Renaultje** [alienatedsec/yi-hack-v5#270]
**Describe the bug**
I've got a iot camera for outside use, and i'm trying the flash custom firmware but it's not flashing

**To Reproduce**
Steps to reproduce the behaviour:
1. Download firmware
2. Copy to sd
3. insert sd and reset camera
4. normal startup

**Expected behaviour**
Led blinkiing while flashing

**Screenshots**
N.A.

**Setupp Details **
 - Firmware Version: 4.0.8_20230713
 - Device: Cctv survaillance camera 1080P with auto tracking
 - Model: unkown

**Technical Details**
No log files

**Comment by alienatedsec** [comment]
Not supported
