### ISSUE TITLE
No web host, no rstp or other settings when sd card out

### ISSUE THREAD

**Issue by pszewello** [alienatedsec/yi-hack-v5#271]
**Describe the bug**
When the sd card is removed, I lose access to the web interface, rstp stops working, basically only the oroginal app works... with yi-hacks4 the sd card was only needed to flash. Is it different here?

**To Reproduce**
Steps to reproduce the behaviour:
1) Have the camera working with SD card
2) Remove SD card, and restart camera
3) No more access to web host, nothing is working as expected

**Expected behaviour**
Like in yi-hacks-4 I expect that the flashed firmare has everyghing needed, and does not relay on SD card beeing inserted

**Set Up Details (please complete the following information):**
 - Firmware Version: latest
 - Device: YI HOME 1080P

**Comment by alienatedsec** [comment]
Hi @pszewello 
I am sorry to disappoint you #267
