### ISSUE TITLE
Crying detection

### ISSUE THREAD

**Issue by Cryonic90** [alienatedsec/yi-hack-v5#295]
I see in the latest pre-release that the baby crying detection is back.
But when I try to turn it on, it turns the option off after a few minutes and doesn't work.
The same is the case for sound detection, any changes to that are reverted as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'settings'
2. Click on 'baby crying detect'

**Expected behaviour**
Baby crying detection to stay on and working

**Set Up Details (please complete the following information):**
 - Firmware Version: 0.4.1a
 - Device: yi_cloud_dome_1080p
 - Model: 5FUS

**Comment by waleed-alharthi** [comment]
I confirm having the same issue with 0.4.1a
Camera is Dome 1080p
I'll try setting up a dirty trigger on home assistant to switch it on when it goes off, hoping it won't backfire.
