### ISSUE TITLE
 yi-cloud dome camera 1080p number 5FUSY

### ISSUE THREAD

**Issue by mirasu** [alienatedsec/yi-hack-v5#296]
hello

I have a yi-cloud dome camera 1080p number 5FUSY
I think this project supports it, but I don't see the necessary files that I have to save to the SD card next to the folder.
How do I get the necessary files?

If not, can someone tell me if some other project doesn't support it?

thank you

**Comment by clutchthrower** [comment]
Go to the Releases and scroll down till you find 0.3.8

Download the file for your camera, and upon extracting it, you will find the other 2 (very sneaky) files you need.
