### ISSUE TITLE
reflect the fact that the rootfs partition and home partition are from 0.3.8 in the documantation

### ISSUE THREAD

**Issue by oferfrid** [alienatedsec/yi-hack-v5#297]
Thanks for posting. It would be GREAT if the official how-to docs included this step.

_Originally posted by @pvcraven in https://github.com/alienatedsec/yi-hack-v5/discussions/288#discussioncomment-7018388_

**Comment by alienatedsec** [comment]
Thanks @oferfrid 

I am happy to update documentation, and due to my limited time (stated here #248) anyone is more than welcome to submit a PR to make things quicker and easier.

**Comment by alienatedsec** [comment]
@oferfrid I hope this [commit](https://github.com/alienatedsec/yi-hack-v5/commit/38c0cf6b28b7101e19a0f5677f7b297f1d40d0b4) makes it easier to follow

**Comment by oferfrid** [comment]
Looks great 👍
