### ISSUE TITLE
firmware,  how to get it, not full description.

### ISSUE THREAD

**Issue by Andrej104104** [alienatedsec/yi-hack-v5#303]
help me pls to get firmware files,   cat find them  searched all over the internet,  only dead sites , cant find firmware that is needed.
thnx

"
    Save both files and the yi-hack-v5 folder on root path of microSD card.

![image](https://github.com/alienatedsec/yi-hack-v5/assets/96086678/9232af8c-5212-4941-8e28-6bac5fa57070)
"

**Comment by alienatedsec** [comment]
@Andrej104104 I hope this [commit](https://github.com/alienatedsec/yi-hack-v5/commit/38c0cf6b28b7101e19a0f5677f7b297f1d40d0b4) makes it easier to follow
