### ISSUE TITLE
unbrick yi camera 12CN

### ISSUE THREAD

**Issue by wankio** [alienatedsec/yi-hack-v5#307]
well several years ago i just flash wrong firmware in yi-hack for one of my yi camera, it just stucked in yellow light, no matter how i try to reset and put "1.8.5.1K_201508311131" home file into root of microSD

today i just connected it into UART , follow by this video https://www.youtube.com/watch?v=3e8jXuxiRzY
when i try to do last step to access bash shell but it always stucked at this part : https://pastebin.com/NhSxxZfK

**Comment by alienatedsec** [comment]
@wankio 
How did you accidentally break it? Please describe exactly what you did and maybe we can reverse your steps :)
