### ISSUE TITLE
yi dome 1080 seems to not read microsd

### ISSUE THREAD

**Issue by dum-skywalker** [alienatedsec/yi-hack-v5#33]
I've downloaded the hack to the root of a fat32 formatted card.
I poweroff the camera, install the micro sd card, and when i poweron, the camera does the startup cicle but doesn't seem to enter firmware uploading process.
Anyway to check if card problem? I used previously same card to install yi-hack-v4 in another camera, and everything worked.
Thanks.

edit: camera works with the yi app, and recognizes the microSD as "in good conditions" in the configuration part.

**Comment by alienatedsec** [comment]
What camera? Model xxUS? @dum-skywalker

**Comment by dum-skywalker** [comment]
it is BFUS

**Comment by alienatedsec** [comment]
@dum-skywalker sorry, not supported - try Allwinner releases
