### ISSUE TITLE
[0.4.1.e] - Yi Home 27US - Unable to Flash

### ISSUE THREAD

**Issue by Minims** [alienatedsec/yi-hack-v5#334]
**Describe the bug**

I have follow the how to and format a 16GB in FAT32. I have tried the windows solution, but also with my own tools. I have tried more than 10 times and everytime the led stay yellow. I have wait about 30min.

there is no new files on the SD.

On reboot without the sd card or with the 0.4.1d sd, it’ok.

**To Reproduce**
Steps to reproduce the behaviour:
Follow the 0.4.1e guide

**Expected behaviour**
be able to flash

**Comment by alienatedsec** [comment]
@roleoroleo is your model also not flashing with the release files?

**Comment by roleoroleo** [comment]
Not tested yet.
I'll let you know as soon as possible.

**Comment by alienatedsec** [comment]
I will need to make the home image smaller - it's too big to accept flashing

**Comment by roleoroleo** [comment]
I compared your image with mine and there is a big difference in size: about 1,5 MB.
The main problem is the library /home/app/libcrypto.so.1.1
I don't know why but in my image is not present.

**Comment by alienatedsec** [comment]
I'll have a look in the evening.

**Comment by alienatedsec** [comment]
> The main problem is the library /home/app/libcrypto.so.1.1

@roleoroleo did you mean `/home/lib/libcrypto.so.1.1`? It must be there as needed by the latest WPA unless you are not compiling it and it's not being replaced.

![image](https://github.com/alienatedsec/yi-hack-v5/assets/73167064/121307b6-1f44-4f06-b7e1-70aa593718f2)

**Comment by alienatedsec** [comment]
[New release - 0.4.1f](https://github.com/alienatedsec/yi-hack-v5/releases/tag/0.4.1f)

**Comment by Minims** [comment]
Thanks, i was able to flash the camera. It seems working excepted the known bug of the pre-release.

**Comment by alienatedsec** [comment]
@Minims is 0.4.1g also flashing and not connecting on your 27US?

**Comment by Minims** [comment]
@alienatedsec 0.4.1g is flashing and wifi is ok on my side with wpa2

**Comment by alienatedsec** [comment]
@Minims 
When you type wpa_supplicant in the console, does it report v2.10?

**Comment by Minims** [comment]
@alienatedsec Yes
```
/home/yi-hack-v5 # uptime
 14:48:36 up 44 min,  load average: 4.97, 4.79, 4.39

/home/yi-hack-v5 # cat /tmp/wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant
ap_scan=1
network={
ssid="********"
scan_ssid=1
proto=WPA RSN
key_mgmt=WPA-PSK
pairwise=CCMP TKIP
group=CCMP TKIP
psk="********"
}

/home/yi-hack-v5 # wpa_supplicant
Successfully initialized wpa_supplicant
wpa_supplicant v2.10
Copyright (c) 2003-2022, Jouni Malinen <j@w1.fi> and contributors
```
