### ISSUE TITLE
yi outdoor 1080p firmware 9.0.26.05_202011201756

### ISSUE THREAD

**Issue by nonome1** [alienatedsec/yi-hack-v5#34]
Hello,

I tried the V5 and it doesn't read the SD card I tried a 16g, 32g in class 10. Have you ever had a positive feedback on this firmware?

**Comment by alienatedsec** [comment]
It's an Allwinner platform. V5 won't work on it.

**Comment by nonome1** [comment]
thanks for the answer but the all version works but the video stream for ha in rtsp is really not that great and only works on firefox.  thanks anyway.  I will resell this camera

**Comment by kwirk** [comment]
@nonome1  Home Assistant built-in RTSP isn't very good. Have you tried [AlexxIT/WebRTC](https://github.com/AlexxIT/WebRTC)? It works great.
