### ISSUE TITLE
When i remove the SD card the web gui not open..

### ISSUE THREAD

**Issue by wackyesolution** [alienatedsec/yi-hack-v5#378]
**Describe the bug**
After flashed tha yi-hack-v5 on my yi dome the webpage with custom setting is avaiable on the ip of the camera trought browser.
But if I remove the SD card with the custom firmware flash file in the internal of the memory, it does not start on webgui but is only avaiable the camera on the Yi Home officiall app.

I want to remove the SD card and keep the custom fw directly on the camera memory, is it possible with yi hack v5?
Previusly on the Yi-home hack v4 it was possible..

**To Reproduce**
Steps to reproduce the behaviour:
1. install cfw on the sd card.
2. with sd card all work fine.
3. if i remove the sd card and restart the webgui does not appear.

**Expected behaviour**
I expect to use my camera with cfw without any sd card into.

**Set Up Details (please complete the following information):**
 - Firmware Version: 1.9.1.0J_201809191135
 - Device: Yi Home (not 1080 model) 
 - Model: [e.g., yhs.1916]
i used this one for flashing :

- Yi Dome	rootfs_v201	home_v201	1.9.1.0J_201809191135

**Comment by alienatedsec** [comment]
Please read #267
