### ISSUE TITLE
Wrong Hostname

### ISSUE THREAD

**Issue by ljlongwing** [alienatedsec/yi-hack-v5#38]
Using 0.3.0

On the Home Page the 'Hostname' doesn't match what I have specified under Config 'Hostname'.  The value that exists on the home page is a value configured with a different firmware

**Comment by alienatedsec** [comment]
@ljlongwing Should be resolved through this [commit](https://github.com/alienatedsec/yi-hack-v5/commit/2f5159b70d174ab190666abdc261289b18a5a874)
