### ISSUE TITLE
Can't See RTSP stream 

### ISSUE THREAD

**Issue by rcstreamer** [alienatedsec/yi-hack-v5#380]
Hi,
I need to hack my camera to put the stream inside OBS.

I downloaded and installed everything in my Yi Dome following your instructions.
I have access to the Yi hack5 page and I turned the RTSP ON saving the configuration(I opened 554 TCP port on the router too).

The problem is when I click on the RTSP link in the home page it tries to open VLC and  I get errors, VLC can't open the link :(
(Inside the official app the camera works well, from Yi hack5 page I can only get snapshots correctly)

Did I miss something??

**Comment by penguin86** [comment]
This happens also on my Yi Dome and to some other cameras, like Yi Dome 1080p (see https://github.com/alienatedsec/yi-hack-v5/issues/422 ) and some others, see https://github.com/alienatedsec/yi-hack-v5/issues/321
Anyone has any hint on how to debug the issue?
