### ISSUE TITLE
Config not stored

### ISSUE THREAD

**Issue by tremebundo** [alienatedsec/yi-hack-v5#387]
I have two Yi Home 1080. I have upgraded them from v4.
Any change I made in the config settings seem to be saved but they are lost at the next reboot.
Any hint?

Hack (SD) Firmware Version | 0.4.1
Baseline Firmware Version | 0.4.1
Base Version | 2.1.0.0E_201809191630
Model Suffix | yi_home_1080p
Hardware ID | 48US

**Comment by tremebundo** [comment]
I used Safari instead of Chrome and it worked. I think it had to do something with cookies
Solved.
Sorry.

**Comment by sommo** [comment]
thank you
