### ISSUE TITLE
I cant get my camera to flash

### ISSUE THREAD

**Issue by M-Dot613** [alienatedsec/yi-hack-v5#389]
**What im using:**
16gb Micro SD
Yi Home 1080p

**Whats Happening**
I follow all the steps. first i format the card to FAT32, then i upload the 2 files and the 1 folder, next i insert the SD card and and power cable. The yellow light comes on then the blue light blinks for 5 seconds and that's it.

the current firmware on the camera is 12.2.0.2_202212191129 not sure if that's the issue.

**Comment by alienatedsec** [comment]
Try https://github.com/roleoroleo/yi-hack-Allwinner-v2
