### ISSUE TITLE
Cannot flash Yi Home 47US camera, light gets stuck on solid yellow and never moves forward.

### ISSUE THREAD

**Issue by getutsav** [alienatedsec/yi-hack-v5#390]
**Describe the bug**
Unable to flash 47US to yi hack v5, light on camera gets stuck on solid yellow and never moves forward. Tried multiple SD cards. Camera works fine after reboot and removing the card.

**Comment by alienatedsec** [comment]
@getutsav it happened many times, so please ensure your files are downloaded properly. 
Mac users used to struggle the most. Use Windows for downloading and unpacking files.
