### ISSUE TITLE
Crontab doest work at @reboot

### ISSUE THREAD

**Issue by Piceeeeeee** [alienatedsec/yi-hack-v5#394]
So i have a cusstom script to send recording to telegram that work manually, but when i put it on crontab -e trough ssh or in the webpage, it never lauch at start.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to etc, crontab , root
2. edit crontab
3. add "@reboot /bin/sh /pathtoscript.sh"
4. Reboot

**Expected behaviour**
The script doest get launch at all

Hack (SD) Firmware Version | 0.4.1

Baseline Firmware Version | 0.4.1
Base Version | 1.8.7.0F_201809191400
Model Suffix | yi_home

**Additional context**
i am just testing it but if you want the script here it is, it work when i lauch it manualkly or in the background.
`#!/bin/bash

# Configuration
TOKEN=""
CHAT_ID=""
BASE_DIRECTORY="/tmp/sd/record"
INTERVAL=60

# Function to send a Telegram message
send_telegram_message() {
    local message=$1
    echo "Sending Telegram notification: $message"
    response=$(curl -k -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
        -d chat_id=$CHAT_ID \
        -d text="$message")
    echo "Response: $response"
    
    if [[ $response == *"error"* ]]; then
        echo "Error in response: $response"
    fi
}

# Function to send a file to Telegram
send_telegram_file() {
    local file=$1
    echo "Sending file to Telegram: $file"
    response=$(curl -k -s -F chat_id=$CHAT_ID -F document=@"$file" "https://api.telegram.org/bot$TOKEN/sendDocument")
    echo "Response: $response"
    
    if [[ $response == *"error"* ]]; then
        echo "Error in response: $response"
    fi
}

# Function to get the latest directory
get_latest_directory() {
    ls -1d "$BASE_DIRECTORY"/*/ | sort | tail -n 1
}

# Function to get the latest file in a directory
get_latest_file() {
    local dir=$1
    ls -1t "$dir"/*.mp4 | sort | tail -n 1
}

# Initial latest directory and file
latest_directory=$(get_latest_directory)
latest_file=$(get_latest_file "$latest_directory")
echo "Initial latest directory: $latest_directory"
echo "Initial latest file: $latest_file"

# Monitor the directory for new files
while true; do
    echo "Checking for new files..."
    current_directory=$(get_latest_directory)
    current_file=$(get_latest_file "$current_directory")
    echo "Current latest directory: $current_directory"
    echo "Current latest file: $current_file"
    
    if [ "$current_file" != "$latest_file" ]; then
        echo "New file detected: $current_file in directory $current_directory"
        send_telegram_message "New file detected: $current_file in $current_directory"
        send_telegram_file "$current_file"
        latest_directory=$current_directory
        latest_file=$current_file
    fi

    sleep $INTERVAL
done
`

**Comment by reef-actor** [comment]
Might be related to #112? cron config gets loaded from system.conf and the was (is?) a bug that was causing the cron entries to be truncated. Perhaps check the contents of that file?
