### ISSUE TITLE
Snapshots impossible to use

### ISSUE THREAD

**Issue by dreimer1986** [alienatedsec/yi-hack-v5#396]
**Describe the bug**
Snapshots don't show up for quite a while on website and Home Assistant's FFMPEG runs into an timeout.

**To Reproduce**
Steps to reproduce the behaviour:
Check Snapshot site in webUI and grab some popcorn or do the same with camera.snapshot service under HA.

**Expected behaviour**
At least a bit faster, like the two internal Allwinner 2 based YI cams I use, too would be perfect.

**Screenshots**
-

**Set Up Details (please complete the following information):**
 - Firmware Version: 0.4.1
 - Device: Yi Outdoor
 - Model: 6CUS

**Additional context**
Add any other context about the problem here. If any other systems are involved, please complete the following:
 - Name of the system: Home Assistant
 - Version: 2024.9.0b1

**Technical Details**
Please add any technical details (e.g., log files)
I dont think you wanna see the ffmpeg error in HA and regarding a bunch of stale reports the problem is known already.

Is this chipset really that muich slower than the Allwiner 2? If not, maybe @roleoroleo has a clue why this whole thing is so overloaded and thus feels slow on website (for example on saving settings) and is way too slow to pass a snapshot to HA

EDIT: Small experiment to get what I need. I use wget console command in HA. Here my results:

wget http://192.168.181.116/cgi-bin/snapshot.sh?res=high --timeout=600 -O /config/downloads/doorbell.jpg

Took 29 sec to create. 1920x1080 is fine, bit the speed is... phew...

wget http://192.168.181.116/cgi-bin/snapshot.sh?res=low&watermark=yes --timeout=600 -O /config/downloads/doorbell.jpg

Took 10 sec to create. 640x360 is still a bit too much of pixel art ^^...

wget http://192.168.181.116/cgi-bin/snapshot.sh?res=low --timeout=600 -O /config/downloads/doorbell.jpg

Took 3 sec to create. 320x192 is useless though...

Correct me if I am wrong, but if it can shrink it down then it should already have a full size pic for that, right? It looks like the save process is SLOW in general, this would explain the ultra slow saving of the config, too...

**Comment by alienatedsec** [comment]
@dreimer1986 Try using the YI method from the settings. At this moment, I will have no time to explore how to improve the speed, but I am happy to take any pull request under consideration.

**Comment by dreimer1986** [comment]
I guess you mean the download way I did? Alright, already done. Not 100% stable as sometimes the file is 0 Bytes, but it works with some additional error collecting. I am no big Linux embedded guy, but I will go on a bug hunt, too. Maybe some luck and good karma will help me finding something :D
