### ISSUE TITLE
Wifi connection problem - v0.4.1

### ISSUE THREAD

**Issue by mbox1** [alienatedsec/yi-hack-v5#398]
The camera doesn't connect to wifi after turning on and restarts in loop.
The wifi AP is Unifi with WPA2 protocol and password, this happens since version 0.4.1c, version 0.4.1b is fine. 
Device YI HOME Outdoor 4CUS.

**Comment by alienatedsec** [comment]
Please try the following: Create a folder `wpa` in the `yi-hack-v5` folder and copy the content of the zip file onto it.
[wpa.zip](https://github.com/user-attachments/files/17062982/wpa.zip)

```
/yi-hack-v5/wpa/wpa_cli
/yi-hack-v5/wpa/wpa_supplicant
/yi-hack-v5/wpa/wpa_supplicant_upgrade
```

Reboot

The same applies to #371 and #386

**Comment by mbox1** [comment]
It's working, the camera is now connecting. 
Thanks

**Comment by mbox1** [comment]
It's working, the camera is connecting now.
Thanks

**Comment by alienatedsec** [comment]
Now documented in https://github.com/alienatedsec/yi-hack-v5/releases/tag/0.4.1
