### ISSUE TITLE
How to set presets for 'Yi 1080p Dome'

### ISSUE THREAD

**Issue by PatrickR68** [alienatedsec/yi-hack-v5#40]
Hello all, 

how can I set presets? 
I found only the possibility to call existing presets. 

Many thanks,
Patrick

**Comment by roleoroleo** [comment]
If I'm not wrong you can set presets only using the original app.

**Comment by PatrickR68** [comment]
With original app it's possible. 
It tooks a picture and store it somewhere. 
But finally it will store the number of steps of the engine.

**Comment by PatrickR68** [comment]
1) Does someone know where the data of the camera presets are stored? 
2) Could they manipulated?

**Comment by roleoroleo** [comment]
I think they are stored in a raw flash partition.
But the format is unknow.
