### ISSUE TITLE
How to find out if m.Lilliput-001 go, comma is compatible with one of the cameras in this project?

### ISSUE THREAD

**Issue by PatrickR68** [alienatedsec/yi-hack-v5#52]
Hello,

I have a Lilliput-001 from go, comma.

Exist a way to find out which version could be compatible to this variant?

From optic point of you, it should be a "1080 Dome".

It has a different USB connector, round connector instead of microUSB.
Also an LAN connection too.

Many thanks,

Patrick

**Comment by alienatedsec** [comment]
Hi @PatrickR68 
If it has LAN, it is not likely to be Hi3518e chipset. What firmware version you have? I could see v7.xxx in some [videos](https://youtu.be/ab5s48Cn_rc?t=405)

**Comment by PatrickR68** [comment]
@alienatedsec 
Yes you are right. 
7.0.00.73A_201812031453
