### ISSUE TITLE
Where are the releases?

### ISSUE THREAD

**Issue by tunerooster** [alienatedsec/yi-hack-v5#6]
I went to download, but says no releases in the "release" link.
I am looking for:
```
Yi Outdoor	rootfs_h30	home_h30
```

No problem if it is "coming". I just can hardly wait!  :)

**Comment by MiSSHeaDShoT** [comment]
You can grab a beta from the old repo here: https://github.com/alienatedsec/yi-hack-v4/releases .

**Comment by alienatedsec** [comment]
https://github.com/alienatedsec/yi-hack-v5/releases/tag/0.3.0
