### ISSUE TITLE
Timestamp not embedded in video

### ISSUE THREAD

**Issue by hhopjh** [alienatedsec/yi-hack-v5#62]
This is very interesting project with great potential!

Is there any way to add timestamp to RTSP video stream?
versio: v0.3.1 - BETA

Cheers!

**Comment by alienatedsec** [comment]
Let's work on the initial performance issues first - I will let you know about further progress soon

**Comment by jffz** [comment]
Is there any hope for this feature ?

**Comment by g1za** [comment]
I think this can be closed as there is now the option to add timestamp on the stream (even if not reflecting the specified timezone)

**Comment by alienatedsec** [comment]
Fixed/Added with `0.4.1i`
