### ISSUE TITLE
Malformed audio on some recorded files

### ISSUE THREAD

**Issue by korayal** [alienatedsec/yi-hack-v5#68]
I'm not sure how to replicate this, but when checking out some recorded videos that I've synced to somewhere else, I noticed some recordings have 2x audio while the video is at normal speed. so after around  20 or 25 seconds there are no audio in those files.

This issue persists on the file stored in the SD card too.

**Comment by alienatedsec** [comment]
Please check #70 as could be related

**Comment by alienatedsec** [comment]
Another one to check #63 as there could be not enough RAM to manage I/O and data recording

**Comment by alienatedsec** [comment]
`0.3.6` to fix many and similar performance issues
