### ISSUE TITLE
Only menu tab visible and working nothing else.

### ISSUE THREAD

**Issue by hyp716** [alienatedsec/yi-hack-v5#69]
Only menu tab visible nothing else although yi app is working.
27US / YHS-113-IR Yi home 720 [cam spec].FW: 1.8.7.0F_201809191400.
tried updating from Yi hack v4.
![Sc2106_LI](https://user-images.githubusercontent.com/85710441/121602410-e3a95d80-ca64-11eb-8240-87bf3b89f4f9.jpg)

**Comment by alienatedsec** [comment]
Try [ip address]:8080

**Comment by hyp716** [comment]
its working  thanks
