### ISSUE TITLE
12CN

### ISSUE THREAD

**Issue by wilb** [alienatedsec/yi-hack-v5#7]
Great to see this work being progressed. Just an offer to say I've got some 12CN cameras still running the early fritz hack, happy to do some testing of the v5 hack on them if you feel there's any chance of it supporting that hardware.

**Comment by Arkady23** [comment]
I think there is a different SDK on 12CN. Here is a project with cameras with Hi3518ev200 chip. And 12CN and 22CN have Hi3518ev100 chip. Perhaps the assembly will suit you https://github.com/SnakeSel/YiHome_camera_http.
