### ISSUE TITLE
No audio ?

### ISSUE THREAD

**Issue by Maastodonte** [alienatedsec/yi-hack-v5#74]
Hi, I'm from yi-hack-v4 and then new to the yi-hack-v5.

I flashed smoothlly the v5 on my Yi Cloud Dome 1080p.
After a quick tour I'm wondering if there is a way to get a separate audio input from the camera like in the v4 with a uri like /ch0_2.aac ?
It is quite handy with a baby :)

Thanks for your answers.

I won't mind either if there is already a flux with audio and video together ;)

**Comment by pkishino** [comment]
yeah, just migrated and discovered NO audio..thats quite a bummer :/ I only use onvif/rtsp and not the yi app..connected via agentdvr to record

**Comment by pkishino** [comment]
i tried setting rtsp_audio=yes in the system.conf but no difference

**Comment by akbaryahya** [comment]
yes it only sounds through mi app and record files but when connecting via rtsp there is no sound, * use YI Outdoor Camera

**Comment by MACscr** [comment]
Yikes, so this custom firmware doesn't do audio at all on rtsp streams? Obviously it would need to be a stream. No idea how two different streams would even be useful even if it was provided.

**Comment by kapabel** [comment]
I've got the same problem. No sound :(

**Comment by alienatedsec** [comment]
The next release `0.3.7(?)` will support audio over RTSP

**Comment by MACscr** [comment]
> 

So i guess still no audio? the 0.3.7 beta notes are a bit confusing. Says audio is next, so its not included?

**Comment by alienatedsec** [comment]
> So i guess still no audio? the 0.3.7 beta notes are a bit confusing. Says audio is next in the 0.3.7 notes, so its not included as you had previously mentioned?

Unfortunately, I had to release another version with no audio, but the RTSP sound is already in the code. However, there are problems with HA if Audio is enabled as the platform does not support the audio format. I will think if it is worth releasing this way

**Comment by MACscr** [comment]
What is the audio format? Why isn’t it in an rtsp format that the generic camera feature of HA can use?- MarkOn Jan 3, 2023, at 9:13 AM, alienatedsec ***@***.***> wrote:﻿

So i guess still no audio? the 0.3.7 beta notes are a bit confusing. Says audio is next in the 0.3.7 notes, so its not included as you had previously mentioned?

Unfortunately, I had to release another version with no audio, but the RTSP sound is already in the code. However, there are problems with HA if Audio is enabled as the platform does not support the audio format. I will think if it is worth releasing this way

**Comment by Loafdude** [comment]
Is it possible to enable audio in the current build through configuration or does it require a new release?

**Comment by alienatedsec** [comment]
@Loafdude new release - the code is right there

**Comment by Loafdude** [comment]
Yes I see the code is in master.
Is there a guide to setting up a dev environment anywhere? Or could someone compile current master for y20?

**Comment by Loafdude** [comment]
OK I was able to compile. (Yikes that SDK needs a lot of patching!)

Enabling audio seems to break both the low and high quality streams on my builds.
I've disabled both cloud, onvif. Only things enabled are SSH, RTSP and Audio.

VLC begins to play back then I loose audio and video becomes very laggy.
VLC Statistics show:
![image](https://user-images.githubusercontent.com/17401709/229991338-5da40349-a7e5-4003-a1e1-82d0ad6d8253.png)

Disabling audio plays back 100% normally.

It could be my build. Perhaps someone can confirm? 
I'm using a Home 1080p.

The h264grabber -r audio is only using 1.3% cpu. 
Nothing seems out of line there.

Perhaps the audio stream is malformed and VLC is choking on it?

I understand it's experimental. Just trying to help out!

**Comment by Loafdude** [comment]
Oh I forgot to mention that the audio only stream appears to work fine

**Comment by alienatedsec** [comment]
@Loafdude @Maastodonte I need a couple more days to release another version with audio support.

**Comment by Loafdude** [comment]
No problem, let me know if I can be helpful. I will test once available.
