### ISSUE TITLE
Yi 1080p Outdoor, not able to connect to IP

### ISSUE THREAD

**Issue by vadiro** [alienatedsec/yi-hack-v5#77]
Hi,
I have updated the camera from v4, and it seems to have updated OK, as I am able to connect to it via Yi app, but I can't connect to its IP.
I have a Deco M5 which had a dedicated IP for it, confirmed by checking the Yi app, so I am looking at the right IP, but the web interface is not connecting.
I have tried in Firefox, Chrome and Edge.

**Comment by iMrLopez** [comment]
Try adding the port `:8080` at the end of the ip... it wont connect directly from the ip
