### ISSUE TITLE
Is there a way to use the web interface without a sd card?

### ISSUE THREAD

**Issue by iMrLopez** [alienatedsec/yi-hack-v5#78]
I was wondering if it is possible to use the hack without a sd card?

I noticed that if I enable the RTSP and MQTT and restart the camera without the SD card the config is being saved in the sd card somehow because the RTSP is disabled again, but if I insert the sd camera it works as it should

**Comment by NunchakusLei** [comment]
I'm wondering the same thing. Do you find a solution, yet?

**Comment by iMrLopez** [comment]
Nah, there is no solution to this, seems like the firmware that runs the webserver (and the hack itself) is too heavy to be stored in the camera. I bought 4 sd cards, the smallest ones I found, just to have the hack stored there and installed them on my cameras 🤷
