### ISSUE TITLE
[yi dome 1080p] camera looses cloud access and stops recording at exact equal hour every hour

### ISSUE THREAD

**Issue by majkers** [alienatedsec/yi-hack-v5#80]
Hello,
I think I have a critical bug. My camara yi dome 1080p Hardware Id 65US with firmware 0.3.1 is disconnecting from cloud and stops recording for an undisclosed period of time at exact equal hour every hour. You can see this in a screenshot from yi app below:
![screen](https://user-images.githubusercontent.com/21099773/124385576-953f5580-dcd6-11eb-8420-e3e7364e8def.jpg)
As You cas see I can not rewind to those blank periods and from web page videos are not available too.

As You already know I have cloud enabled and camera continuosly records videos. Beside that I use RTSP stream in Home Assistant. It is not working either during that time so as SSH and FTP. Only PING is working

What else do you need from me? For me it is critical. I thing I will have to get back to the previous hack cause it was workinh well before. 

I use original power supply and I don't  suspect my sd card to break cause it happens exactly at equal hour. I don't have any cron job.

**Comment by alienatedsec** [comment]
too old to investigate `0.3.6` fixes many issues
