### ISSUE TITLE
22eu version not flashing

### ISSUE THREAD

**Issue by Yury-MonZon** [alienatedsec/yi-hack-v5#82]
I can't flash 22eu version, which was updated to the latest version through the app. On the other hand, I remember flashing it with earliest versions of yi-hack. I've tried to flash v5 and v3 - no luck here. Any hints or ideas? 

If it is not possible - I'll try to bruteforce it's telnet pass via uart cable and see what is going on there.

**Comment by alienatedsec** [comment]
Make sure the card is 32GB and FAT32

**Comment by Yury-MonZon** [comment]
> Make sure the card is 32GB and FAT32
Yes, it is.
