### ISSUE TITLE
[ YI Home 1080 V3 Ai ] Support for FW 8.3.0.0A_201912271707

### ISSUE THREAD

**Issue by Ppatou** [alienatedsec/yi-hack-v5#83]
Hello,
Is camera Yi Home 1080P V3 Ai model 9 FUSY 32 VPIRFMS 200319 supported ?
This is not clear in the explanation 
Camera              | rootfs partition | home partition | Remarks
Yi 1080p Home | rootfs_y20          | home_y20        | Firmware files required for the Yi 1080p Home camera.

What means "Firmware files required for the Yi 1080p Home camera" ? and where can I find it ?
Firmware in the camera FW 8.3.0.0A_201912271707: is that the firmware required ?
Thanks in advance for your answer
Patou

**Comment by alienatedsec** [comment]
Please, check Allwinner and I would say it is clear - 9FUS is not listed in this project.
