### ISSUE TITLE
This Camera can only be used within China Yi Home 720p

### ISSUE THREAD

**Issue by thanhtandl10** [alienatedsec/yi-hack-v5#96]
hi alienatedsec thank you so much
My camera yi home 720p 17cn. i copy all file for sd card. camera update ok. ip camera name yi-hack-v5 . 
But i cant open webpage hack v5 .
My camera "This Camera can only be used within China" only.
I use telnet connet ok. 
plz hlep me.

**Comment by thanhtandl10** [comment]
I reboot camera some time. Camera dont show "This Camera can only be used within China" . connect ok . camera is work OMG thank you . but cant open webpage hack

**Comment by orangpelupa** [comment]
same issue. rebooting the camera didnt fix it.
