### ISSUE TITLE
Local Time Zone not effect for Video Record

### ISSUE THREAD

**Issue by abu9** [alienatedsec/yi-hack-v5#98]
I set the local timezone string in config page but i found the video record still name with GMT0. Status page, watermark works fine.  I try `date` command via ssh, seems Timezone hasn't been updated.
```
/tmp/sd/record # date -u
Sun Sep  5 13:23:07 UTC 2021
/tmp/sd/record # date
Sun Sep  5 13:23:10 UTC 2021
/tmp/sd/record # date -R
Sun, 05 Sep 2021 13:23:20 +0000
/tmp/sd/record # cat /tmp/sd/yi-hack-v5/etc/TZ
HKT-8
/tmp/sd/record # ls /tmp/sd/record/
2021Y09M06D04H  2021Y09M06D05H
```

**Comment by abu9** [comment]
I had removed the timezone setting in web config, the video record is work now.

**Comment by alienatedsec** [comment]
It needs fixing - ill keep that in mind - thanks @abu9
